apiVersion: v1
entries:
  chia-blockchain:
  - apiVersion: v2
    appVersion: 1.2.10
    created: "2021-11-02T22:11:38.9497722-04:00"
    dependencies:
    - name: common
      repository: https://library-charts.k8s-at-home.com
      version: 4.0.1
    description: Chia is a modern cryptocurrency built from scratch, designed to be
      efficient, decentralized, and secure.
    digest: a269c96a16614fe7c8bbc5b416ca4ecfc001eed8b2930d6b28d6eefc0c19da90
    home: https://github.com/anthonytam/Chia-Forks-Docker/tree/master/helm/chia-blockchain
    icon: https://www.chia.net/img/chia_logo.svg
    keywords:
    - chia
    - chia-blockchain
    kubeVersion: '>=1.16.0-0'
    name: chia-blockchain
    sources:
    - https://github.com/Chia-Network/chia-blockchain
    - https://github.com/Chia-Network/chia-docker
    - https://github.com/k8s-at-home/container-images
    urls:
    - https://anthonytam.github.io/Chia-Forks-Docker/helm/chia-blockchain-0.1.0.tgz
    version: 0.1.0
generated: "2021-11-02T22:11:38.946621-04:00"
